### ISSUE TITLE
As a USER, I want to Create, Read, Update and Delete my Todo's

### ISSUE THREAD

**Issue by mikededo** [mikededo/users-todos#2]
## Task

Develop the CRUD endpoints for the `Todo` model.

### Subtasks

> All endpoints need user authentication.

- [x] `GET` `todo/:id`
- [x] `GET` `todo`
- [x] `POST` `todo/:id`
- [x] `PUT` `todo/:id`
- [x] `DELETE` `todo/:id`

> `POST` and `PUT` must have a body with the todo information.
